//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSPagoServicio.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WSPagoServicio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1720.
        /// </summary>
        internal static string banco {
            get {
                return ResourceManager.GetString("banco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SYSTEM.ADMIN.SVRCONN.
        /// </summary>
        internal static string channelName {
            get {
                return ResourceManager.GetString("channelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 549.
        /// </summary>
        internal static string CodConsulta {
            get {
                return ResourceManager.GetString("CodConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 401.
        /// </summary>
        internal static string CodErrorAutorizacion {
            get {
                return ResourceManager.GetString("CodErrorAutorizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 400.
        /// </summary>
        internal static string CodErrorConexion {
            get {
                return ResourceManager.GetString("CodErrorConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 200.
        /// </summary>
        internal static string CodPagoExitoso {
            get {
                return ResourceManager.GetString("CodPagoExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 10.240.66.8.
        /// </summary>
        internal static string hostName {
            get {
                return ResourceManager.GetString("hostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO MQPRO.MQ_VISA_HISTORY VALUES ( .
        /// </summary>
        internal static string InsertVisaHistory {
            get {
                return ResourceManager.GetString("InsertVisaHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        internal static string numberOfMsgs {
            get {
                return ResourceManager.GetString("numberOfMsgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1414.
        /// </summary>
        internal static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM MQPRO.MQ_FORMATOS_DETALLE WHERE CODIGO_MQ_BANCO = .
        /// </summary>
        internal static string query_banco_detalle {
            get {
                return ResourceManager.GetString("query_banco_detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM MQ_FORMATOS.
        /// </summary>
        internal static string query_banco_formato {
            get {
                return ResourceManager.GetString("query_banco_formato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select * from MQPRO.MQ_FORMATOS_INI WHERE CODIGO_MQ_BANCO =.
        /// </summary>
        internal static string query_banco_ini {
            get {
                return ResourceManager.GetString("query_banco_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a QM_ENERGUATE_RECEP.
        /// </summary>
        internal static string queueManagerName {
            get {
                return ResourceManager.GetString("queueManagerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a QL.ENER.VS.ONLINE.
        /// </summary>
        internal static string queueName_Get {
            get {
                return ResourceManager.GetString("queueName_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a QL.VS.ENER.ONLINE.
        /// </summary>
        internal static string queueName_Put {
            get {
                return ResourceManager.GetString("queueName_Put", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visa.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 68ba07abf0d370630620ea43c68fabbd.
        /// </summary>
        internal static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 76B925EF7BEC821780B4B21479CE6482EA415896CF43006050B1DAD101669921.
        /// </summary>
        internal static string UserVisa {
            get {
                return ResourceManager.GetString("UserVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DD1791DB5B28DDE6FBC2B9951DFED4D97B82EFD622B411F1FC16B88B052232C7.
        /// </summary>
        internal static string UserVisaPass {
            get {
                return ResourceManager.GetString("UserVisaPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 090249.
        /// </summary>
        internal static string VisaAuditNumber {
            get {
                return ResourceManager.GetString("VisaAuditNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 00575123.
        /// </summary>
        internal static string VisaMerchant {
            get {
                return ResourceManager.GetString("VisaMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0200.
        /// </summary>
        internal static string VisaMessageTypePago {
            get {
                return ResourceManager.GetString("VisaMessageTypePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0400.
        /// </summary>
        internal static string VisaMessageTypeReversion {
            get {
                return ResourceManager.GetString("VisaMessageTypeReversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 190.149.69.135.
        /// </summary>
        internal static string VisapaymentgwIP {
            get {
                return ResourceManager.GetString("VisapaymentgwIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 012.
        /// </summary>
        internal static string VisaposEntryMode {
            get {
                return ResourceManager.GetString("VisaposEntryMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 77788881.
        /// </summary>
        internal static string VisaTerminalID {
            get {
                return ResourceManager.GetString("VisaTerminalID", resourceCulture);
            }
        }
    }
}
