//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSPagoServicio.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VisaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VisaResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WSPagoServicio.Properties.VisaResource", typeof(VisaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 76B925EF7BEC821780B4B21479CE6482EA415896CF43006050B1DAD101669921.
        /// </summary>
        internal static string UserVisa {
            get {
                return ResourceManager.GetString("UserVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DD1791DB5B28DDE6FBC2B9951DFED4D97B82EFD622B411F1FC16B88B052232C7.
        /// </summary>
        internal static string UserVisaPass {
            get {
                return ResourceManager.GetString("UserVisaPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 090249.
        /// </summary>
        internal static string VisaAuditNumber {
            get {
                return ResourceManager.GetString("VisaAuditNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 00575123.
        /// </summary>
        internal static string VisaMerchant {
            get {
                return ResourceManager.GetString("VisaMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0400.
        /// </summary>
        internal static string VisaMessageTypeAnulacion {
            get {
                return ResourceManager.GetString("VisaMessageTypeAnulacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0202.
        /// </summary>
        internal static string VisaMessageTypeReversa {
            get {
                return ResourceManager.GetString("VisaMessageTypeReversa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0200.
        /// </summary>
        internal static string VisaMessageTypeVenta {
            get {
                return ResourceManager.GetString("VisaMessageTypeVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 190.149.69.135.
        /// </summary>
        internal static string VisapaymentgwIP {
            get {
                return ResourceManager.GetString("VisapaymentgwIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 012.
        /// </summary>
        internal static string VisaposEntryMode {
            get {
                return ResourceManager.GetString("VisaposEntryMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 77788881.
        /// </summary>
        internal static string VisaTerminalID {
            get {
                return ResourceManager.GetString("VisaTerminalID", resourceCulture);
            }
        }
    }
}
